
name: Build Windows EXE (v2.3.6-r6)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pyinstaller app_exact.spec
          if (Test-Path "${{ github.workspace }}\build_exe.py") {
            python "${{ github.workspace }}\build_exe.py" --onefile
          } else {
            Write-Host "build_exe.py not found; skip onefile"
          }
      - uses: actions/upload-artifact@v4
        with:
          name: hx-offline-editor-dist-v2_3_6_r6
          path: dist/**
      - uses: actions/upload-artifact@v4
        with:
          name: hx-offline-editor-exe-onefile-v2_3_6_r6
          path: dist/*.exe
          if-no-files-found: ignore
